name: flutterfast
description: Build Flutter apps fast.
publish_to: none
version: 0.0.4+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  auto_route: ^8.1.3
  collection: ^1.18.0
  crypto: ^3.0.3
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0  
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  sentry_flutter: ^8.1.0
  shared_preferences: ^2.2.3
  simple_mvvm: ^1.0.1
  sign_in_with_apple: ^6.1.0
  transparent_image: ^2.0.1
  universal_io: ^2.2.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.6

  #* Amplitude *#
  amplitude_flutter: ^3.16.2
  #* Amplitude *#

  #* Posthog *#
  posthog_flutter: ^4.4.1
  #* Posthog *#

  #* RSS *#
  http: 1.2.1
  webfeed_revised: ^0.7.2
  #* RSS *#

  #* Subscriptions *#
  purchases_flutter: ^6.29.0
  #* Subscriptions *#

  #* Appwrite *#
  appwrite: ^12.0.3
  #* Appwrite *#

  #* Firebase *#
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.4
  #* Firebase *#

  #* Fanalytics *#
  firebase_analytics: ^10.10.4
  #* Fanalytics *#

  #* Supabase *#
  supabase_flutter: ^2.5.2
  #* Supabase *#

  #* Pocketbase *#
  pocketbase: ^0.18.1
  #* Pocketbase *#

  #* Google Sign In *#
  google_sign_in: ^6.2.1
  #* Google Sign In *#


# Build command
# Dev: dart run ../bin/fast.dart build
# dart run build_runner build --delete-conflicting-outputs
dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  monarch: ^3.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "logo"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
  # windows:
  #   generate: true
  #   image_path: "assets/logo.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  macos:
      generate: true
      image_path: "assets/logo.png"